version: '3.8'

services:
  url_analyzer:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=8000